# Generated by Django 3.2.7 on 2021-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='detail',
            field=models.TextField(default='detail'),
            preserve_default=False,
        ),
    ]
