# Generated by Django 3.2.7 on 2021-09-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_auto_20210926_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsresult',
            name='id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
