# Generated by Django 3.2.7 on 2021-10-03 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_airline_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='over_60',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='under_30',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='under_60',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
