# Generated by Django 3.2.7 on 2021-10-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20211003_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='arrival',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='airlines.arrival'),
        ),
    ]
