# Generated by Django 3.2.7 on 2021-09-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_alter_statisticsresult_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsresult',
            name='airline',
            field=models.CharField(default='erase', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticsresult',
            name='arrival',
            field=models.CharField(default='erase', max_length=50),
            preserve_default=False,
        ),
    ]
