# Generated by Django 3.2.7 on 2021-10-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_review_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='arrival',
            field=models.ForeignKey(default='3WLv22yDUUhtC', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='airlines.arrival'),
        ),
    ]
