# Generated by Django 3.2.7 on 2021-09-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_auto_20210926_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='total_canceled',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='total_delayed',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airline',
            name='total_flight',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statisticsresult',
            name='cancel_rate',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
