# Generated by Django 3.2.7 on 2021-09-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_auto_20210926_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='arrival',
        ),
    ]
