# Generated by Django 3.2.7 on 2021-09-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_auto_20210928_0226'),
        ('airlines', '0005_remove_review_arrival'),
    ]

    operations = [
    ]
