# Generated by Django 3.2.7 on 2021-10-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_alter_review_arrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.RemoveField(
            model_name='arrival',
            name='image_url',
        ),
    ]
